services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=buscavan
    ports:
      - '5433:5432'
    volumes:
      - ./sql-scripts/:/docker-entrypoint-initdb.d/
